version: '3.7'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"  # CQL
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
    driver: local