name: FastAPI Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/genai.backend.fastapi/**'
  workflow_dispatch: # allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/genai.backend.fastapi
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.actor }}/fastapi-backend:latest
      
      - name: Remove old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          cut-off: 1h
          image-names: "fastapi-backend"
          tag-selection: untagged
